// Generated by CoffeeScript 2.0.0-beta4
(function() {
  var conventions;

  conventions = function(opts = {}) {
    var bottom, container, height, innerSize, left, margin, right, size, top, transform, width;
    /* D3 conventions */
    ({width, height, margin, left, top, bottom, right, container} = opts);
    if (margin == null) {
      margin = 10;
    }
    if (left == null) {
      left = margin;
    }
    if (right == null) {
      right = margin;
    }
    if (top == null) {
      top = margin;
    }
    if (bottom == null) {
      bottom = margin;
    }
    if (container != null) {
      ({width, height} = container.node().getBoundingClientRect());
      width -= left + right;
      height -= top + bottom;
    }
    innerSize = {width, height};
    size = {
      width: width + left + right,
      height: height + top + bottom
    };
    margin = {left, right, top, bottom};
    transform = `translate(${left},${top})`;
    return {innerSize, margin, size, transform};
  };

  module.exports = conventions;

}).call(this);
