// Generated by CoffeeScript 2.0.0-beta4
(function() {
  var conventions, scaleLinear;

  ({scaleLinear} = require('d3-scale'));

  conventions = function(opts = {}) {
    var bottom, container, height, innerSize, inset, left, margin, right, size, top, transform, width, x, y;
    /* D3 conventions */
    ({width, height, margin, left, top, bottom, right, container, inset} = opts);
    if (inset == null) {
      inset = true;
    }
    if (margin == null) {
      margin = 10;
    }
    if (left == null) {
      left = margin;
    }
    if (right == null) {
      right = margin;
    }
    if (top == null) {
      top = margin;
    }
    if (bottom == null) {
      bottom = margin;
    }
    if (container != null) {
      inset = true; // We have to be inset because we already know the size
      if (container.node != null) {
        container = container.node();
      }
      ({width, height} = container.getBoundingClientRect());
    }
    if (width == null) {
      width = 800;
    }
    if (height == null) {
      height = 500;
    }
    if (inset) {
      width -= left + right;
      height -= top + bottom;
    }
    innerSize = {width, height};
    size = {
      width: width + left + right,
      height: height + top + bottom
    };
    margin = {left, right, top, bottom};
    transform = `translate(${left},${top})`;
    x = scaleLinear().range([0, width]);
    y = scaleLinear().range([height, 0]);
    return {innerSize, margin, size, transform, x, y};
  };

  module.exports = conventions;

}).call(this);
